//! `hydro-analyze` — a `RUSTC_WORKSPACE_WRAPPER` that measures each `#[kernel]`'s MIR.
//!
//! Invoked by the example's `build.rs` as the wrapper for a marker-gated nested `cargo +nightly
//! build`. Cargo hands it the full, correct `rustc` command for every crate; for the example crate
//! it runs that compile *in process* (adding `-Zalways-encode-mir`) with a StableMIR pass that walks
//! the body of every function tagged `#[hydro_analyze::metrics(kernel = "…")]` and writes one line of
//! metrics per kernel to `$HYDRO_ANALYSIS_OUT`. For every other crate (the dependencies) it just execs
//! the real `rustc`. The pass returns `Continue`, so the crate still compiles and cargo succeeds.
//!
//! All the `rustc_private` code lives in this final binary on purpose: a crate that does
//! `extern crate rustc_driver` can't be imported without hitting "std only shows up once".
#![feature(rustc_private)]

extern crate rustc_driver;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_public;

use std::process::{Command, ExitCode};

use rustc_public::mir::{Statement, StatementKind, TerminatorKind};
use rustc_public::rustc_internal;
use rustc_public::{CrateDef, CrateItem};

fn main() -> ExitCode {
    // Wrapper convention: argv = [self, real_rustc, ...rustc_args].
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() {
        eprintln!("hydro-analyze: expected a rustc command");
        return ExitCode::FAILURE;
    }
    let real_rustc = args.remove(0);

    // The crate to analyze is named by the build helper (`HYDRO_ANALYZE_CRATE`); every other crate in
    // the nested build (the dependencies) is passed straight through to the real compiler.
    let want = std::env::var("HYDRO_ANALYZE_CRATE").ok();
    let is_target = want.is_some()
        && crate_name(&args) == want
        && args.iter().any(|a| a == "--crate-type")
        && !args.iter().any(|a| a.starts_with("--print"))
        && std::env::var_os("HYDRO_ANALYSIS_OUT").is_some();

    if is_target {
        analyze(&args)
    } else {
        // Passthrough: run the real compiler untouched (dependencies, print requests, …).
        let status = Command::new(&real_rustc).args(&args).status();
        match status {
            Ok(s) => ExitCode::from(s.code().unwrap_or(1) as u8),
            Err(e) => {
                eprintln!("hydro-analyze: failed to exec {real_rustc}: {e}");
                ExitCode::FAILURE
            }
        }
    }
}

fn crate_name(args: &[String]) -> Option<String> {
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == "--crate-name" {
            return it.next().cloned();
        }
        if let Some(n) = a.strip_prefix("--crate-name=") {
            return Some(n.to_string());
        }
    }
    None
}

fn analyze(args: &[String]) -> ExitCode {
    // Reuse cargo's exact invocation (sysroot, --extern, -L, features all resolved), plus MIR.
    let mut rustc_args = vec!["rustc".to_string()];
    rustc_args.extend(args.iter().cloned());
    rustc_args.push("-Zalways-encode-mir".to_string());

    let mut cb = Analyzer;
    let r = rustc_driver::catch_fatal_errors(|| rustc_driver::run_compiler(&rustc_args, &mut cb));
    match r {
        Ok(()) => ExitCode::SUCCESS,
        Err(_) => ExitCode::FAILURE,
    }
}

struct Analyzer;

impl rustc_driver::Callbacks for Analyzer {
    fn after_analysis(
        &mut self,
        _compiler: &rustc_interface::interface::Compiler,
        tcx: rustc_middle::ty::TyCtxt<'_>,
    ) -> rustc_driver::Compilation {
        let lines = rustc_internal::run(tcx, collect).unwrap_or_default();
        if let Ok(out) = std::env::var("HYDRO_ANALYSIS_OUT") {
            let mut s = String::from("// @generated by hydro-analyze — do not edit\n");
            for l in &lines {
                s.push_str(l);
                s.push('\n');
            }
            let _ = std::fs::write(out, s);
        }
        // Let the compile finish so cargo is satisfied with the throwaway build.
        rustc_driver::Compilation::Continue
    }
}

/// One `name k=v …` line per tagged kernel. `compute` folds in the statements of the kernel's
/// closures (the bodies of the `|acc,v| …` steps handed to `sum`/`reduce`/`map`), which live in
/// separate MIR items named `…::<kernel>_on::{closure#N}` — invisible to the `_on` body itself but
/// where a combinator kernel's real arithmetic intensity lives.
fn collect() -> Vec<String> {
    use std::collections::HashMap;
    let items = rustc_public::all_local_items();

    struct Kernel {
        name: String,
        on_full: String,
        m: Metrics,
        /// `_on` names this kernel invokes (the callees run under *this* kernel's unroll factor).
        callees: Vec<String>,
    }

    let mut kernels: Vec<Kernel> = Vec::new();
    for item in &items {
        if let Some(name) = kernel_name(item) {
            let callees = item.body().map(|b| callee_fn_names(&b)).unwrap_or_default();
            kernels.push(Kernel { name, on_full: item.name(), m: measure(item), callees });
        }
    }

    // Compute intensity = statements reachable from the kernel's `_on` body: the body, its combinator
    // closures (the `|acc,v| …` steps, separate items named `…_on::{closure#N}`), and the non-kernel
    // helper functions those transitively call — stopping at other kernels' `_on` boundaries (folded
    // separately by composition). This is what stops a kernel that delegates its arithmetic to a plain
    // helper (`activate_poly`) from measuring as an empty map body. (Register pressure — `varying_locals`
    // — is NOT folded this way: peak pressure isn't a reachable-set property, and folding it regressed
    // the light reductions; a register-heavy combinator kernel uses the explicit `unroll` cap instead.)
    let stmts_of: HashMap<String, u64> = items.iter().map(|it| (it.name(), stmt_count(it))).collect();
    let calls_of: HashMap<String, Vec<String>> = items
        .iter()
        .map(|it| (it.name(), it.body().map(|b| all_call_targets(&b)).unwrap_or_default()))
        .collect();
    let kernel_ons: std::collections::HashSet<String> =
        kernels.iter().map(|k| k.on_full.clone()).collect();
    for k in &mut kernels {
        k.m.compute = compute_intensity(&k.on_full, &stmts_of, &calls_of, &kernel_ons);
    }

    // Cross-kernel cost composition: when kernel A calls B via `B_on`, B's reduction runs under A's
    // chosen unroll factor, so A's cap must satisfy B too. Fold the transitive callees' register and
    // compute pressure into each kernel by `max` (the tightest sub-kernel wins). Since every kernel
    // exports the composed value, a chain resolves the whole call tree.
    let idx: HashMap<&str, usize> =
        kernels.iter().enumerate().map(|(i, k)| (k.on_full.as_str(), i)).collect();
    let own: Vec<(u64, u64)> = kernels.iter().map(|k| (k.m.varying_locals, k.m.compute)).collect();
    let callee_ids: Vec<Vec<usize>> = kernels
        .iter()
        .map(|k| k.callees.iter().filter_map(|c| idx.get(c.as_str()).copied()).collect())
        .collect();

    kernels
        .iter()
        .enumerate()
        .map(|(i, k)| {
            let (vl, compute) = composed_pressure(i, &own, &callee_ids, &mut vec![false; own.len()]);
            format!(
                "{} stack_bytes={} varying_locals={} mem_ops={} switches={} calls={} stmts={} compute={}",
                k.name, k.m.stack_bytes, vl, k.m.mem_ops, k.m.switches, k.m.calls, k.m.stmts, compute
            )
        })
        .collect()
}

/// `max` of a kernel's own (varying_locals, compute) with the transitive closure of its callees'.
fn composed_pressure(
    i: usize,
    own: &[(u64, u64)],
    callees: &[Vec<usize>],
    seen: &mut [bool],
) -> (u64, u64) {
    if seen[i] {
        return (0, 0);
    }
    seen[i] = true;
    let (mut vl, mut compute) = own[i];
    for &c in &callees[i] {
        let (cvl, ccompute) = composed_pressure(c, own, callees, seen);
        vl = vl.max(cvl);
        compute = compute.max(ccompute);
    }
    (vl, compute)
}

/// The `…_on` names a body calls directly (the cross-kernel edges). Non-`_on` calls are ignored.
fn callee_fn_names(body: &rustc_public::mir::Body) -> Vec<String> {
    all_call_targets(body).into_iter().filter(|n| n.ends_with("_on")).collect()
}

/// Every function name a body calls (kernels and plain helpers alike).
fn all_call_targets(body: &rustc_public::mir::Body) -> Vec<String> {
    use rustc_public::mir::TerminatorKind;
    use rustc_public::ty::{RigidTy, TyKind};
    let mut out = Vec::new();
    for bb in body.blocks.iter() {
        if let TerminatorKind::Call { func, .. } = &bb.terminator.kind {
            if let Ok(ty) = func.ty(body.locals()) {
                if let TyKind::RigidTy(RigidTy::FnDef(def, _)) = ty.kind() {
                    out.push(def.name());
                }
            }
        }
    }
    out
}

/// Statements reachable from a kernel's `_on` body — the body, its closures (reached by the external
/// combinator, so seeded by name), and the non-kernel local functions they transitively call —
/// stopping at other kernels' `_on` boundaries (folded separately by cross-kernel composition).
fn compute_intensity(
    on_full: &str,
    stmts_of: &std::collections::HashMap<String, u64>,
    calls_of: &std::collections::HashMap<String, Vec<String>>,
    kernel_ons: &std::collections::HashSet<String>,
) -> u64 {
    let mut visited = std::collections::HashSet::new();
    let mut stack: Vec<String> = vec![on_full.to_string()];
    let closure_prefix = format!("{on_full}::");
    for name in stmts_of.keys() {
        if name.contains("{closure") && name.starts_with(&closure_prefix) {
            stack.push(name.clone());
        }
    }
    let mut total = 0;
    while let Some(n) = stack.pop() {
        if !visited.insert(n.clone()) {
            continue;
        }
        total += stmts_of.get(&n).copied().unwrap_or(0);
        for c in calls_of.get(&n).into_iter().flatten() {
            if c != on_full && kernel_ons.contains(c.as_str()) {
                continue;
            }
            if stmts_of.contains_key(c) {
                stack.push(c.clone());
            }
        }
    }
    total
}

fn stmt_count(item: &CrateItem) -> u64 {
    match item.body() {
        Some(b) => b.blocks.iter().map(|bb| bb.statements.len() as u64).sum(),
        None => 0,
    }
}

/// The `kernel = "…"` value if the item carries `#[hydro_analyze::metrics(..)]`.
fn kernel_name(item: &CrateItem) -> Option<String> {
    let path = ["hydro_analyze".to_string(), "metrics".to_string()];
    let attr = item.tool_attrs(&path).into_iter().next()?;
    attr.as_str().split('"').nth(1).map(str::to_string)
}

#[derive(Default)]
struct Metrics {
    stack_bytes: u64,
    varying_locals: u64,
    mem_ops: u64,
    switches: u64,
    calls: u64,
    stmts: u64,
    compute: u64,
}

fn measure(item: &CrateItem) -> Metrics {
    let mut m = Metrics::default();
    let Some(body) = item.body() else { return m };

    for local in body.locals().iter() {
        // Register-pressure proxy: how many varying (SIMD lane-vector) values the body holds.
        if format!("{:?}", local.ty).contains("Varying") {
            m.varying_locals += 1;
        }
    }

    for block in body.blocks.iter() {
        m.stmts += block.statements.len() as u64;
        for stmt in &block.statements {
            m.mem_ops += mem_ops_in(stmt);
        }
        match &block.terminator.kind {
            TerminatorKind::SwitchInt { .. } => m.switches += 1,
            TerminatorKind::Call { .. } => m.calls += 1,
            _ => {}
        }
    }

    m.stack_bytes = mono_stack_bytes(item).unwrap_or(0);
    m
}

/// Memory traffic proxy: assignments whose destination is written through a dereference (a store to
/// `*p`/`slice[i]`), which is what the `noalias` boundary helps LLVM cluster.
fn mem_ops_in(stmt: &Statement) -> u64 {
    if let StatementKind::Assign(place, _rvalue) = &stmt.kind {
        use rustc_public::mir::ProjectionElem;
        if place
            .projection
            .iter()
            .any(|p| matches!(p, ProjectionElem::Deref | ProjectionElem::Index(_)))
        {
            return 1;
        }
    }
    0
}

/// Best-effort concrete frame size of the `ScalarBackend` monomorphization. Returns `None` when the
/// instance can't be resolved (generic const params, external-type resolution) — no decision depends
/// on this, so callers fall back to `0`.
fn mono_stack_bytes(_item: &CrateItem) -> Option<u64> {
    // Monomorphized resolution (Instance::resolve with a constructed `[f32, ScalarBackend]`) is the
    // nightly-fragile part; deferred. Generic-MIR counts drive every current decision.
    None
}
